version: 2.1
jobs:
 build:
   environment:
    - DOCKER_USER: gridtrue
    - DOCKER_PASS: 84a9e1d1-30d5-4eac-b4a8-d6d802a82898
    - DOCKER_TAG: api
   machine: true
   steps:
     - checkout
     # with credentials stored in the UI
     - run: |
         echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
         cd api

     # build the application image
     - run: docker build -t gridtrue/people:$DOCKER_TAG .

     # deploy the image
     - run: docker push gridtrue/people:$DOCKER_TAG
  
     
